// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rki.ImportToSql.Services;

namespace Rki.ImportToSql.Migrations
{
    [DbContext(typeof(RepoTest2))]
    [Migration("20210805115321_MultipleTables")]
    partial class MultipleTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rki.ImportToSql.Models.Domain.Imira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresszusatz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Familienstand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GebDat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gebdat_gesetzt")
                        .HasColumnType("int");

                    b.Property<string>("Geburtsland")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geburtsland_original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Geburtsort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Lfdnr")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ortsteil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sperrvermerk")
                        .HasColumnType("int");

                    b.Property<string>("Staat1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat1_original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat2_original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat3_original")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Staat_agg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strasse_HNR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tranche")
                        .HasColumnType("int");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImiraImport");
                });

            modelBuilder.Entity("Rki.ImportToSql.Models.Domain.Test2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests2");
                });
#pragma warning restore 612, 618
        }
    }
}
